config/routes.rb
PhotogurInClass::Application.routes.draw do
  root :to => 'pictures#index'

  resources :pictures

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # Allow mass-assignment for the attributes title and artist
  attr_accessible :title, :artist, :url
  # Don't confuse this with attr_accessor

  validates :title, :presence => true
  validates :url,   :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController# NOT: ActionController::Base

  def index
    @pictures = Picture.all
  end

  def show
    # params = {
    #   :id => "5"
    # }
    @picture = Picture.find params[:id]
  end

  def new
    @picture = Picture.new
  end

  def create
    # params = {
    #   :url => "http://fdasfdsafds",
    #   :title => "some title",
    #   :artist => "some artist"
    # }

    # Solution 1
    # @picture = Picture.new
    # @picture.url = params[:url]
    # @picture.title = params[:title]
    # @picture.artist = params[:artist]

    # Solution2 - needs attr_accessible on the model
    # success = @picture.create(:title => params[:title], :url => params[:url], :artist => params[:artist])

    @picture = Picture.new(params[:picture])
    # Create doesn't return a boolean, always returns an instance of a picture.
    if @picture.save # returns true or false 
      redirect_to pictures_path
    else
      # There was an error on the form
      flash.now[:error] = "Could not save the picture. Please try again."
      render :new
      # redirect_to new_picture_path  # ---> Loses the data.
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end


  def update
    # Example params looks like this:
    # params = {
    #   :id => "4",
    #   :picture => {
    #     :title => "some title here ",
    #     :url => "http://some-url-here.com/",
    #     :artist => "Artist name"
    #   }
    # }

    # get the picture I want to update
    @picture = Picture.find(params[:id])

    # The update_attributes below is passing in a hash
    # The hash is nicely put together by Rails thanks to form_for
    # This is what is happening on line 70 below.
    # @picture.update_attributes({
    #   :title => "!!! ",
    #   :name => "Khurram",
    #   :url => "...."
    # })

    if @picture.update_attributes(params[:picture]) # Why?

      # redirect_to "/pictures/#{@picture.id}"
      # redirect_to picture_path(@picture.id)
      # redirect_to picture_path(@picture)
      redirect_to @picture
      # named routes are convenience methods created
      # by ruby to help us navigate the application
    else
      # do something else
      # redirect_to "/pictures" 
      redirect_to pictures_path
    end
  end













end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotogurInClass</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav">
    <ul>
      <li><%= link_to "Pictures", pictures_path %></li>
      <li><%= link_to "New Picture", new_picture_path %></li>
    </ul>
  </div>
  <div class="clear"></div>
  <%= yield %>
  

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
  <p>
    <label>Artist</label><br>
    <!-- <input type="text" name="artist"/> -->
    <%= f.text_field "artist" %>
  </p>
  <p>
    <label>Title</label><br>
    <!-- <input type="text" name="title"/> -->
    <% if @picture.errors.messages[:title] %>
      <%= @picture.errors.messages[:title][0] %>
    <% end %>

    <!-- <p class="error">can't be blank</p> -->
    <%= f.text_field "title" %>
  </p>
  <p>
    <label>URL</label><br>
    <!-- <p class="error">can't be blank</p> -->
    <!-- <input type="text" name="url"/> -->
    <%= @picture.errors[:url].join(" ")%>
    <%= f.text_field "url" %>
  </p>
  <p>
    <!-- <input type="submit"/> -->
    <%= f.submit "Save" %>
  </p>


<% end %>

app/views/pictures/edit.html.erb
<h1>Edit a picture</h1>

<%= render :partial => "form" %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>

<!--a href="/pictures/new">New Picture</a-->
<!-- <a href="<%= new_picture_path %>">New Picture</a> -->
<!-- <%= link_to "New Picture", new_picture_path %> -->

<% @pictures.each do |picture| %>
  <h2><%= picture.title %></h2>
  <%= button_to "Edit", edit_picture_path(picture), :method => :get%>
  <!-- <a href="<%= edit_picture_path(picture) %>">Edit</a> -->
  <p><%= picture.artist %></p>
  <!-- <a href="<%= picture_path(picture)%>"> -->
    <!-- <img src="<%= picture.url %>"> -->
  <!-- </a> -->
  <%= link_to picture_path(picture) do %>
    <img src="<%= picture.url%>">
  <% end %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>

<div class="errors">
  <%= flash[:error] %>
</div>

<%= render :partial => "form" %>

app/views/pictures/show.html.erb
<h1><%= @picture[:title] %></h1>
<img src="<%= @picture[:url] %>">